from pydantic import BaseModel, Field
from typing import Literal, Optional
from datetime import datetime
import uuid


class Alerta(BaseModel):
    """
    Alerta generada por el sistema de monitoreo.
    / Alert generated by the monitoring system.
    / התראה שנוצרה על ידי מערכת הניטור.
    """
    alerta_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    maquina_id: str
    tipo: Literal[
        "temperatura_alta", "vibracion_alta", "rpm_anomalo",
        "paro_inesperado", "orden_retrasada", "mantenimiento_preventivo"
    ]
    severidad: Literal["info", "warning", "critical"] = "warning"
    mensaje: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    atendida: bool = False
    atendida_por: Optional[str] = None     # user_id quien la atendió
    tenant_id: str


class AlertaUpdate(BaseModel):
    atendida: bool = True
    atendida_por: Optional[str] = None
