# FabriSense - Mosquitto MQTT Broker Config
# DEV LOCAL ONLY - No usar en producción sin TLS

listener 1883
allow_anonymous true

# En producción usar TLS 1.2+ con credenciales:
# listener 8883
# cafile /mosquitto/config/ca.crt
# certfile /mosquitto/config/server.crt
# keyfile /mosquitto/config/server.key
# tls_version tlsv1.2
# allow_anonymous false
# password_file /mosquitto/config/passwd

persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_type error
log_type warning
log_type notice
